name: Integration tests

on:
  pull_request:

jobs:
  integration-tests:
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    with:
      load-test-enabled: false
      load-test-run-args: "-e LOAD_TEST_HOST=localhost"
      zap-enabled: true
      zap-cmd-options: '-T 60 -z "-addoninstall jython" --hook "/zap/wrk/tests/zap/hook.py"'
      zap-target: localhost
      zap-target-port: 80
      zap-rules-file-name: "zap_rules.tsv"
      trivy-fs-enabled: true
      trivy-image-config: "trivy.yaml"
      self-hosted-runner: true
      self-hosted-runner-label: "edge"
      juju-channel: '3/stable'
      channel: '1.32-strict/stable'
